2021-03-26 09:12:29,957	INFO head.py:52 -- Dashboard head grpc address: 192.168.10.2:65150
2021-03-26 09:12:29,958	WARNING dashboard.py:98 -- [Errno 2] Dashboard build directory not found. If installing from source, please follow the additional steps required to build the dashboard(cd python/ray/new_dashboard/client && npm install && npm ci && npm run build): 'C:\\Users\\j_theocharides\\PycharmProjects\\Ray_test\\venv\\lib\\site-packages\\ray\\new_dashboard\\client\\build'
2021-03-26 09:12:29,960	ERROR head.py:167 -- Connect to GCS failed: GCS address not found., retry...
2021-03-26 09:12:31,964	INFO head.py:162 -- Connect to GCS at b'192.168.10.2:65155'
2021-03-26 09:12:31,974	INFO utils.py:202 -- Get all modules by type: DashboardHeadModule
2021-03-26 09:12:32,034	WARNING reporter_agent.py:36 -- Install gpustat with 'pip install gpustat' to enable GPU monitoring.
2021-03-26 09:12:32,060	WARNING tune_head.py:22 -- tune module is not available: No module named 'pandas'
2021-03-26 09:12:32,060	INFO head.py:131 -- Loading DashboardHeadModule: <class 'ray.new_dashboard.modules.job.job_head.JobHead'>
2021-03-26 09:12:32,060	INFO head.py:131 -- Loading DashboardHeadModule: <class 'ray.new_dashboard.modules.log.log_head.LogHead'>
2021-03-26 09:12:32,060	INFO head.py:131 -- Loading DashboardHeadModule: <class 'ray.new_dashboard.modules.logical_view.logical_view_head.LogicalViewHead'>
2021-03-26 09:12:32,061	INFO head.py:131 -- Loading DashboardHeadModule: <class 'ray.new_dashboard.modules.reporter.reporter_head.ReportHead'>
2021-03-26 09:12:32,061	INFO head.py:131 -- Loading DashboardHeadModule: <class 'ray.new_dashboard.modules.stats_collector.stats_collector_head.StatsCollector'>
2021-03-26 09:12:32,061	INFO head.py:131 -- Loading DashboardHeadModule: <class 'ray.new_dashboard.modules.tune.tune_head.TuneController'>
2021-03-26 09:12:32,061	INFO head.py:135 -- Loaded 6 modules.
2021-03-26 09:12:32,063	INFO head.py:213 -- Dashboard head http address: 127.0.0.1:8265
2021-03-26 09:12:32,064	INFO head.py:227 -- <ResourceRoute [GET] <PlainResource  /> -> <function Dashboard.get_index at 0x00000299679C44C8>
2021-03-26 09:12:32,064	INFO head.py:227 -- <ResourceRoute [GET] <PlainResource  /favicon.ico> -> <function Dashboard.get_favicon at 0x00000299680174C8>
2021-03-26 09:12:32,064	INFO head.py:227 -- <ResourceRoute [GET] <PlainResource  /jobs> -> <function JobHead.get_all_jobs[cache ttl=2, max_size=128] at 0x00000299680871F8>
2021-03-26 09:12:32,064	INFO head.py:227 -- <ResourceRoute [GET] <DynamicResource  /jobs/{job_id}> -> <function JobHead.get_job[cache ttl=2, max_size=128] at 0x0000029968087438>
2021-03-26 09:12:32,064	INFO head.py:227 -- <ResourceRoute [GET] <PlainResource  /log_index> -> <function LogHead.get_log_index at 0x0000029968087F78>
2021-03-26 09:12:32,064	INFO head.py:227 -- <ResourceRoute [GET] <PlainResource  /log_proxy> -> <function LogHead.get_log_from_proxy at 0x000002996808F0D8>
2021-03-26 09:12:32,064	INFO head.py:227 -- <ResourceRoute [GET] <PlainResource  /logical/actor_groups> -> <function LogicalViewHead.get_actor_groups at 0x00000299680A43A8>
2021-03-26 09:12:32,064	INFO head.py:227 -- <ResourceRoute [GET] <PlainResource  /logical/actors> -> <function LogicalViewHead.get_all_actors[cache ttl=2, max_size=128] at 0x00000299680A6318>
2021-03-26 09:12:32,064	INFO head.py:227 -- <ResourceRoute [GET] <PlainResource  /logical/kill_actor> -> <function LogicalViewHead.kill_actor at 0x00000299680A64C8>
2021-03-26 09:12:32,064	INFO head.py:227 -- <ResourceRoute [GET] <PlainResource  /api/launch_profiling> -> <function ReportHead.launch_profiling at 0x00000299680C3828>
2021-03-26 09:12:32,064	INFO head.py:227 -- <ResourceRoute [GET] <PlainResource  /api/ray_config> -> <function ReportHead.get_ray_config at 0x00000299680C3798>
2021-03-26 09:12:32,064	INFO head.py:227 -- <ResourceRoute [GET] <PlainResource  /api/cluster_status> -> <function ReportHead.get_cluster_status at 0x00000299680C3948>
2021-03-26 09:12:32,065	INFO head.py:227 -- <ResourceRoute [GET] <PlainResource  /nodes> -> <function StatsCollector.get_all_nodes[cache ttl=2, max_size=128] at 0x00000299681029D8>
2021-03-26 09:12:32,065	INFO head.py:227 -- <ResourceRoute [GET] <DynamicResource  /nodes/{node_id}> -> <function StatsCollector.get_node[cache ttl=2, max_size=128] at 0x0000029968102C18>
2021-03-26 09:12:32,065	INFO head.py:227 -- <ResourceRoute [GET] <PlainResource  /memory/memory_table> -> <function StatsCollector.get_memory_table at 0x0000029968102DC8>
2021-03-26 09:12:32,065	INFO head.py:227 -- <ResourceRoute [GET] <PlainResource  /memory/set_fetch> -> <function StatsCollector.set_fetch_memory_info at 0x0000029968102EE8>
2021-03-26 09:12:32,065	INFO head.py:227 -- <ResourceRoute [GET] <PlainResource  /node_logs> -> <function StatsCollector.get_logs at 0x000002996810E048>
2021-03-26 09:12:32,065	INFO head.py:227 -- <ResourceRoute [GET] <PlainResource  /node_errors> -> <function StatsCollector.get_errors at 0x000002996810E168>
2021-03-26 09:12:32,065	INFO head.py:227 -- <ResourceRoute [GET] <PlainResource  /tune/info> -> <function TuneController.tune_info at 0x000002996812D288>
2021-03-26 09:12:32,065	INFO head.py:227 -- <ResourceRoute [GET] <PlainResource  /tune/availability> -> <function TuneController.get_availability at 0x000002996812D3A8>
2021-03-26 09:12:32,065	INFO head.py:227 -- <ResourceRoute [GET] <PlainResource  /tune/set_experiment> -> <function TuneController.set_tune_experiment at 0x000002996812D4C8>
2021-03-26 09:12:32,065	INFO head.py:227 -- <ResourceRoute [GET] <PlainResource  /tune/enable_tensorboard> -> <function TuneController.enable_tensorboard at 0x000002996812D678>
2021-03-26 09:12:32,065	INFO head.py:227 -- <ResourceRoute [GET] <StaticResource  /logs -> WindowsPath('C:/Users/j_theocharides/PycharmProjects/Ray_test/temp/session_2021-03-26_09-12-27_265259_4336/logs')> -> <bound method StaticResource._handle of <StaticResource  /logs -> WindowsPath('C:/Users/j_theocharides/PycharmProjects/Ray_test/temp/session_2021-03-26_09-12-27_265259_4336/logs')>>
2021-03-26 09:12:32,065	INFO head.py:228 -- Registered 23 routes.
2021-03-26 09:12:32,066	INFO datacenter.py:65 -- Purge data.
2021-03-26 09:12:32,067	INFO reporter_head.py:138 -- Subscribed to RAY_REPORTER:*
2021-03-26 09:12:32,067	INFO job_head.py:73 -- Subscribed to JOB:*
2021-03-26 09:12:32,067	INFO job_head.py:78 -- Getting all job info from GCS.
2021-03-26 09:12:32,067	INFO stats_collector_head.py:176 -- Subscribed to ACTOR:*
2021-03-26 09:12:32,068	INFO stats_collector_head.py:186 -- Getting all actor info from GCS.
2021-03-26 09:12:32,068	INFO stats_collector_head.py:284 -- Subscribed to <_Sender name:b'RAY_LOG_CHANNEL', is_pattern:False, receiver:<Receiver is_active:True, senders:1, qsize:0>>
2021-03-26 09:12:32,068	INFO stats_collector_head.py:307 -- Subscribed to b'ERROR_INFO:*'
2021-03-26 09:12:32,069	INFO stats_collector_head.py:213 -- Received 0 actor info from GCS.
2021-03-26 09:12:32,069	INFO job_head.py:89 -- Received 0 job info from GCS.
2021-03-26 09:12:32,765	INFO stats_collector_head.py:296 -- Received a log for 192.168.10.2 and autoscaler
2021-03-26 09:12:34,108	ERROR web_protocol.py:393 -- Unhandled exception
Traceback (most recent call last):
  File "C:\Users\j_theocharides\PycharmProjects\Ray_test\venv\lib\site-packages\aiohttp\web_protocol.py", line 485, in start
    resp, reset = await task
  File "C:\Users\j_theocharides\PycharmProjects\Ray_test\venv\lib\site-packages\aiohttp\web_protocol.py", line 440, in _handle_request
    reset = await self.finish_response(request, resp, start_time)
  File "C:\Users\j_theocharides\PycharmProjects\Ray_test\venv\lib\site-packages\aiohttp\web_protocol.py", line 591, in finish_response
    await prepare_meth(request)
  File "C:\Users\j_theocharides\PycharmProjects\Ray_test\venv\lib\site-packages\aiohttp\web_fileresponse.py", line 115, in prepare
    st = await loop.run_in_executor(None, filepath.stat)
  File "C:\Users\j_theocharides\AppData\Local\Programs\Python\Python37\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\j_theocharides\AppData\Local\Programs\Python\Python37\lib\pathlib.py", line 1183, in stat
    return self._accessor.stat(self)
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\Users\\j_theocharides\\PycharmProjects\\Ray_test\\venv\\lib\\site-packages\\ray\\new_dashboard\\client\\build\\index.html'
2021-03-26 09:12:35,254	ERROR web_protocol.py:393 -- Unhandled exception
Traceback (most recent call last):
  File "C:\Users\j_theocharides\PycharmProjects\Ray_test\venv\lib\site-packages\aiohttp\web_protocol.py", line 485, in start
    resp, reset = await task
  File "C:\Users\j_theocharides\PycharmProjects\Ray_test\venv\lib\site-packages\aiohttp\web_protocol.py", line 440, in _handle_request
    reset = await self.finish_response(request, resp, start_time)
  File "C:\Users\j_theocharides\PycharmProjects\Ray_test\venv\lib\site-packages\aiohttp\web_protocol.py", line 591, in finish_response
    await prepare_meth(request)
  File "C:\Users\j_theocharides\PycharmProjects\Ray_test\venv\lib\site-packages\aiohttp\web_fileresponse.py", line 115, in prepare
    st = await loop.run_in_executor(None, filepath.stat)
  File "C:\Users\j_theocharides\AppData\Local\Programs\Python\Python37\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\j_theocharides\AppData\Local\Programs\Python\Python37\lib\pathlib.py", line 1183, in stat
    return self._accessor.stat(self)
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\Users\\j_theocharides\\PycharmProjects\\Ray_test\\venv\\lib\\site-packages\\ray\\new_dashboard\\client\\build\\index.html'
2021-03-26 09:12:40,282	ERROR web_protocol.py:393 -- Unhandled exception
Traceback (most recent call last):
  File "C:\Users\j_theocharides\PycharmProjects\Ray_test\venv\lib\site-packages\aiohttp\web_protocol.py", line 485, in start
    resp, reset = await task
  File "C:\Users\j_theocharides\PycharmProjects\Ray_test\venv\lib\site-packages\aiohttp\web_protocol.py", line 440, in _handle_request
    reset = await self.finish_response(request, resp, start_time)
  File "C:\Users\j_theocharides\PycharmProjects\Ray_test\venv\lib\site-packages\aiohttp\web_protocol.py", line 591, in finish_response
    await prepare_meth(request)
  File "C:\Users\j_theocharides\PycharmProjects\Ray_test\venv\lib\site-packages\aiohttp\web_fileresponse.py", line 115, in prepare
    st = await loop.run_in_executor(None, filepath.stat)
  File "C:\Users\j_theocharides\AppData\Local\Programs\Python\Python37\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\j_theocharides\AppData\Local\Programs\Python\Python37\lib\pathlib.py", line 1183, in stat
    return self._accessor.stat(self)
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\Users\\j_theocharides\\PycharmProjects\\Ray_test\\venv\\lib\\site-packages\\ray\\new_dashboard\\client\\build\\index.html'
2021-03-26 09:12:44,578	ERROR web_protocol.py:393 -- Unhandled exception
Traceback (most recent call last):
  File "C:\Users\j_theocharides\PycharmProjects\Ray_test\venv\lib\site-packages\aiohttp\web_protocol.py", line 485, in start
    resp, reset = await task
  File "C:\Users\j_theocharides\PycharmProjects\Ray_test\venv\lib\site-packages\aiohttp\web_protocol.py", line 440, in _handle_request
    reset = await self.finish_response(request, resp, start_time)
  File "C:\Users\j_theocharides\PycharmProjects\Ray_test\venv\lib\site-packages\aiohttp\web_protocol.py", line 591, in finish_response
    await prepare_meth(request)
  File "C:\Users\j_theocharides\PycharmProjects\Ray_test\venv\lib\site-packages\aiohttp\web_fileresponse.py", line 115, in prepare
    st = await loop.run_in_executor(None, filepath.stat)
  File "C:\Users\j_theocharides\AppData\Local\Programs\Python\Python37\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\j_theocharides\AppData\Local\Programs\Python\Python37\lib\pathlib.py", line 1183, in stat
    return self._accessor.stat(self)
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\Users\\j_theocharides\\PycharmProjects\\Ray_test\\venv\\lib\\site-packages\\ray\\new_dashboard\\client\\build\\index.html'
